#define _double_
#define _maintest_
#define _mydouble_
#define _myvao_
#define _mybufferobj_
#define _mydrawCube_
#define _movelight_
#define _NateLight_
#define _mycolorMat_
#define _shade_1_
#define _opengl_8th_1_
#define _althorim_1_
#define _algothrim_2_
#define _algothrim_3_
#define _algothrim_4_